version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "lzma-native"
      - dependency-name: "osu-parser"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      twurple:
        patterns:
          - "@twurple/*"

      rendering:
        patterns:
          - "@napi-rs/canvas"
          - "chart.js"
          - "jimp"

      osu:
        patterns:
          - "node-osr"
          - "rosu-pp-js"
          - "ojsama"

      discord:
        patterns:
          - "discord.js"

      devDependencies:
        dependency-type: "development"
